options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-keywords: 2
  no-color-literals: 2
  no-combinators: 0
  no-css-comments: 2
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format:
    - 2
    -
      convention: ^([a-z](\-{1}[a-z])?)*((\-{2})(([A-Z](\-{1}[A-Z])?)|([a-z](\-{1}[a-z])?))*)?
      convention-explanation: Please use http://pointnorth.io/ naming conventions
  function-name-format:
    - 2
    -
      convention: ^([a-z](\-{1}[a-z])?)*((\-{2})(([A-Z](\-{1}[A-Z])?)|([a-z](\-{1}[a-z])?))*)?
      convention-explanation: Please use http://pointnorth.io/ naming conventions
  id-name-format: 0
  mixin-name-format:
    - 2
    -
      convention: ^([a-z](\-{1}[a-z])?)*((\-{2})(([A-Z](\-{1}[A-Z])?)|([a-z](\-{1}[a-z])?))*)?
      convention-explanation: Please use http://pointnorth.io/ naming conventions
  placeholder-name-format:
    - 2
    -
      convention: ^([a-z](\-{1}[a-z])?)*((\-{2})(([A-Z](\-{1}[A-Z])?)|([a-z](\-{1}[a-z])?))*)?
      convention-explanation: Please use http://pointnorth.io/ naming conventions
  variable-name-format:
    - 2
    -
      convention: ^([a-z](\-{1}[a-z])?)*((\-{2})(([A-Z](\-{1}[A-Z])?)|([a-z](\-{1}[a-z])?))*)?
      convention-explanation: Please use http://pointnorth.io/ naming conventions

  # Style Guide
  attribute-quotes: 2
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    -
      style: stroustrup
      allow-single-line: false
  clean-import-paths: 2
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  # TODO: Revert to 2 once https://github.com/sasstools/sass-lint/pull/677 lands
  nesting-depth:
    - 2
    -
      max-depth: 3
  property-sort-order: 2
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
