'use strict';

const Promise = require('bluebird');
const path = require('path');
const config = require('config');
const uuid = require('uuid');
const titleize = require('underscore.string/titleize');
const humanize = require('underscore.string/humanize');

const fs = Promise.promisifyAll(require('fs-extra'));


const wikiGen = (labels, user, repo) => {
  const host = config.github.api.host === 'api.github.com' ? 'github.com' : config.github.api.host;
  const file = path.join(process.cwd(), 'wiki', user, repo, 'Label-Style-Guide.md');
  let wiki = `[![Issue Label Style Guide](https://${host}/${user}/${repo}/wiki/labels.png?${uuid.v4()})](https://${host}/${user}/${repo}/wiki/labels.png)`;

  wiki += '\n\n';
  wiki += 'In order to improve organization and tracking of issues, the following labels should be used as described.';
  wiki += '\n\n';

  wiki += Object.keys(labels).map(label => {
    let section = `## ${titleize(humanize(label))}`;
    section += '\n\n';

    if (labels[label].description) {
      section += labels[label].description;
      section += '\n\n';
    }

    section += labels[label].labels.map(tag => {
      return `* \`${tag}\``;
    }).join('\n');

    return section;
  }).join('\n\n');

  wiki += '\n\n';
  wiki += '---';
  wiki += '\n\n';

  wiki += `Label Style Guide generated by [Reparo](${config.server.host}). (Reparo [on GitHub](https://github.com/Snugug/reparo))`;

  return fs.outputFileAsync(file, wiki);
};

module.exports = wikiGen;
